--- 
- name: 天猫
  md: "http://markdown.4ye.me/z1ei2y6c"
  site: "http://www.tmall.com/"
  url: "http://detail.tmall.com/item.htm?id=15593325475&spm=a1z0k.7385961.1997985097.d4918997.lTDqPh&_u=rkkbfj13db&mt="

- name: 京东
  md: "http://markdown.4ye.me/klxVBaYz"
  site: "http://www.jd.com/"
  url: "http://item.jd.com/1082403.html"



- name: 亚马逊（中国）
  md: "http://markdown.4ye.me/dwpFM336"
  site: "http://www.amazon.cn/"
  url: "http://www.amazon.cn/gp/product/B007ZY5GV2/ref=s9_simh_gw_p79_d14_i2_gs9w?pf_rd_m=A1AJ19PSB66TGU&pf_rd_s=center-2&pf_rd_r=0072J7PVAHGXQ2KXBTNA&pf_rd_t=101&pf_rd_p=248108232&pf_rd_i=899254051"



- name: 凡客
  md: "http://markdown.4ye.me/KAGHbgz2"
  site: "http://www.vancl.com/"
  url: "http://item.vancl.com/1684304.html#ref=zt_zhenzhiku-9229-0-0-v|hp-hp-1-r_4-v:n"


- name: 当当
  md: "http://markdown.4ye.me/Sh5kEhfY"
  site: "http://www.dangdang.com/"
  url: "http://product.dangdang.com/22788959.html#ddclick_reco_book"



- name: 1号店
  md: "http://markdown.4ye.me/unEbYpEy"
  site: "http://www.yhd.com/"
  url: "http://item.yhd.com/item/1884193?tp=2025.0.983.0.8.KlQWfFA-10-D5lua"



- name: AliceInMod
  md: "http://markdown.4ye.me/k2CAyyJI"
  site: "http://www.aliceinmod.com/"
  url: "http://www.aliceinmod.com/?product-5621.html"




- name: 易迅
  md: "http://markdown.4ye.me/GTH2qw0w"
  site: "http://www.yixun.com/"
  url: "http://item.yixun.com/item-1918368.html?YTAG=1.100031206&cp-ptss=1815-3-1918368"


- name: 宜家
  md: "http://markdown.4ye.me/aPckCMRZ"
  site: "http://www.ikea.com/cn/zh/"
  url: "http://www.ikea.com/cn/zh/catalog/products/40281630/"



- name: 趣玩
  md: "http://markdown.4ye.me/DIT6WpP3"
  site: "http://www.quwan.com/"
  url: "http://www.quwan.com/goods_2013-42938.html?FM=lastlike"




- name: 好乐买
  md: "http://markdown.4ye.me/VxrScW1o"
  site: "http://www.okbuy.com/"
  url: "http://www.okbuy.com/p-anta/detail-shoe-17116591.html"





- name: 薄荷糯米葱
  md: "http://markdown.4ye.me/ulxcoBmm"
  site: "http://www.brandnewchina.cn/"
  url: "http://www.brandnewchina.cn/getProduct.htm?productid=18722&color=RED"





- name: NOP
  md: "http://markdown.4ye.me/qk1BET4J"
  site: "http://www.nop.cn/"
  url: "http://www.nop.cn/product-2737.html"


- name: 优集品
  md: "http://markdown.4ye.me/qpzmysKR"
  site: "http://www.ujipin.com/"
  url: "http://www.ujipin.com/g-i15937.html?track=home-time-p2"




- name: 国美在线
  md: "http://markdown.4ye.me/r9Nq88R0"
  site: "http://www.gome.com.cn/"
  url: "http://www.gome.com.cn/product/9133498332.html"


- name: 丽芙家居
  md: "http://markdown.4ye.me/HZA1hrIy"
  site: "http://www.lifevc.com/"
  url: "http://www.lifevc.com/item/11875#ref_src=gssv"




- name: 无印良品（中国）
  md: "http://markdown.4ye.me/hREmA1RY"
  site: "http://www.muji.com.cn/"
  url: "http://www.muji.com.cn/cn/store/goods/4548076448341"




- name: YOHO!有货
  md: "http://markdown.4ye.me/r25NsdRV"
  site: "http://www.yohobuy.com/"
  url: "http://item.yohobuy.com/product/pro_40359_62325/HeiTouYuMaoXiangLian.html"




- name: 新蛋中国
  site: "http://www.newegg.cn/"
  url: "http://www.newegg.cn/Product/A6D-2VX-05H.htm?neg_sp=Home-_-A6D-2VX-05H-_-YouLike"





- name: 欧舒丹中国
  md: "http://markdown.4ye.me/rEtHAkVb"
  site: "http://www.loccitane.cn/"
  url: "http://www.loccitane.cn/cherry-blossom-solid-perfume,90,2,34817,309403.htm#s=34818"



- name: 凡夫
  md: "http://markdown.4ye.me/DjHDln4B"
  site: "http://www.itruelife.com/"
  url: "http://www.itruelife.com/product/300101003.html"




- name: 兰蔻（中国）
  md: "http://markdown.4ye.me/BXdMdSDM"
  site: "http://www.lancome.com.cn/lancome/_zh/_cn/index.aspx"
  url: "http://www.lancome.com.cn/lancome/_zh/_cn/lancome/skincare/the-essence-of/genifique-ls00081.aspx"



- name: KnewOne
  md: "http://markdown.4ye.me/se6Q3xiC"
  site: "https://knewone.com/"
  url: "https://knewone.com/things/vojo-neng-liang-cha-tou"



- name: 理肤泉
  md: "http://markdown.4ye.me/ftK8jAFA"
  site: "http://www.larocheposay.com.cn/"
  url: "http://www.larocheposay.com.cn/store/chanpinxilie/shuhuanpenwu/lifuquanshuhuanpenwu300ml.html"



- name: 良仓
  md: "http://markdown.4ye.me/yhsMxRN8"
  site: "http://www.iliangcang.com/"
  url: "http://www.iliangcang.com/i/goods/?id=34752"




- name: 唯品会
  md: "http://markdown.4ye.me/WUY5QNGR"
  site: "http://www.vip.com/"
  url: "http://www.vip.com/detail-383475-50536007.html?f=0|0|0|1"



- name: Amazon
  md: "http://markdown.4ye.me/ki2wsCb5"
  site: "http://www.amazon.com/"
  url: "http://www.amazon.com/gp/product/B00P1SYWLY/ref=s9_pop_gw_g121_i5?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=desktop-2&pf_rd_r=1A1GZDJ2R6ZMMT9KTNJX&pf_rd_t=36701&pf_rd_p=1970555362&pf_rd_i=desktop"




- name: Fab
  md: "http://markdown.4ye.me/R16G5TOK"
  site: "http://www.fab.com/"
  url: "http://fab.com/product/virgo-necklace-turquoise-493741/?pref[]=designer%7Ccarla-de-la-cruz-jewelry&ref=designer&pos=3"




- name: ebay
  md: "http://markdown.4ye.me/JaPk6BFD"
  site: "http://www.ebay.com/"
  url: "http://www.ebay.com/itm/Radio-Flow-Lexon-Bleu-/251634701185?&_trksid=p2056016.l4276"





- name: 大众点评网
  md: "http://markdown.4ye.me/j2Oi9SJu"
  site: "http://www.dianping.com/"
  url: "http://www.dianping.com/shop/15861615"





- name: Yelp
  md: "http://markdown.4ye.me/FFXUhy7T"
  site: "http://www.yelp.com/"
  url: "http://www.yelp.com/biz/sous-beurre-kitchen-san-francisco-2"


- name: 豆瓣阅读
  md: "http://markdown.4ye.me/oJTtqI27"
  site: "http://read.douban.com/"
  url: "http://read.douban.com/ebook/8305815/?icn=index-gallery"



- name: 豆瓣读书  
  md: "http://markdown.4ye.me/pLVEXcqQ"
  site: "http://book.douban.com"
  url: "http://book.douban.com/subject/25862578/"




- name: 多看阅读
  md: "http://markdown.4ye.me/ZisezjfX"
  site: "http://www.duokan.com/"
  url: "http://www.duokan.com/book/42790"




- name: 豆瓣电影
  md: "http://markdown.4ye.me/IS0XuIU0"
  site: "http://movie.douban.com/"
  url: "http://movie.douban.com/subject/6875263/"




- name: 时光网
  md: "http://markdown.4ye.me/UfsKAK9l/1"
  site: "http://www.mtime.com/"
  url: "http://movie.mtime.com/204906/"




- name: Imdb
  md: "http://markdown.4ye.me/zEQpwdb2/1"
  site: "http://www.imdb.com/"
  url: "http://www.imdb.com/title/tt1661199/?ref_=rvi_tt"




- name: 安卓市场
  md: "http://markdown.4ye.me/Pd7XyOXR"
  site: "http://apk.hiapk.com/"
  url: "http://apk.hiapk.com/appinfo/com.tencent.mm"




- name: 安智市场
  md: "http://markdown.4ye.me/PdvGHJJl"
  site: "http://www.anzhi.com/"
  url: "http://www.anzhi.com/soft_2122818.html"



- name: 应用汇
  md: "http://markdown.4ye.me/Gg7tXH8a"
  site: "http://www.appchina.com/"
  url: "http://www.appchina.com/app/com.linekong.cjad.yyh"



- name: 豌豆荚
  md: "http://markdown.4ye.me/RpFBYjsI"
  site: "http://www.wandoujia.com/"
  url: "http://www.wandoujia.com/apps/com.gewara"



- name: 机锋市场
  md: "http://markdown.4ye.me/ek8OrGkq"
  site: "http://apk.gfan.com/"
  url: "http://apk.gfan.com/Product/App721206.html"



- name: 应用宝
  md: "http://markdown.4ye.me/IFWsnVr0"
  site: "http://android.myapp.com/"
  url: "http://android.myapp.com/myapp/detail.htm?apkName=com.vanchu.apps.guimiquan"



- name: App Store（中国）
  md: "http://markdown.4ye.me/CGPT4gZM"
  site: "http://itunes.apple.com/cn/genre/ios/id36?mt=8"
  url: "https://itunes.apple.com/cn/app/bad-piggies/id533451786?mt=8"



- name: iTunes Store - 播客（中国）
  md: "http://markdown.4ye.me/vCVWLVuJ"
  site: "https://itunes.apple.com/cn/genre/bo-ke/id26?mt=2"
  url: "https://itunes.apple.com/cn/podcast/wei-zhi-tian-xia/id398155040?mt=2"





- name: iTunes Store - 图书（中国）
  md: "http://markdown.4ye.me/bj8ypybt"
  site: "https://itunes.apple.com/cn/genre/tu-shu/id38?mt=11"
  url: "https://itunes.apple.com/cn/book/xi-xiang-ji/id894592940?mt=11"




- name: 豆瓣移动应用
  md: "http://markdown.4ye.me/nTMTIgDS"
  site: "http://www.douban.com/"
  url: "http://www.douban.com/subject/25890156/"



- name: 淘宝
  md: "http://www.taobao.com/"
  site: "http://www.taobao.com/"
  url: "http://item.taobao.com/item.htm?spm=a219r.lm5179.0.0.yViRpx&id=43782883043&ns=1&abbucket=17"





